### PR TITLE
Add the search feature

### PR DESCRIPTION
**Pull request by Malizor**

### CODE REVIEW

**Comment by swenner** [comment]
Thank you for your great work!

**Comment by Malizor** [comment]
@swenner : what do you think of doing a proper first release for the plugin now?

**Comment by GuillaumeHM** [comment]
Hello,

I'm very interested in the search feature so I checked out the last version of master branch where you enabled the feature and I installed it on my Debian Stretch. The 'Arte+7' tag appears now in list of search engines but when I use it I get a blank page. Comparatly, the Youtube search engine works well.

It seems some content search works fine (see corresponding online content page) :
* *Celte* gives content of http://www.arte.tv/fr/videos/066316-000-A/l-enigme-de-la-tombe-celte
* *ARTE* give a lot of various results

But a lot of other don't :
* *soirée*, *indienne*, *Anoushka*, *anoushka*, *Shankar* are not working for http://www.arte.tv/fr/videos/067083-000-A/une-soiree-indienne-avec-anoushka-shankar-et-patricia-kopatchinskaja
* *Waro*, *waro*, *Suds* are not working for http://www.arte.tv/fr/videos/068918-005-A/danyel-waro-aux-suds-a-arles
* *road*, *Kilkenny* are not working for http://www.arte.tv/fr/videos/073946-000-A/high-road-to-kilkenny
* *festival* give some results but is not working for http://www.arte.tv/fr/videos/054325-005-A/romane-chave-creation-au-festival-django-reinhardt

Do you have the same behavior ? Am I missing something ?

**Comment by Malizor** [comment]
Hi @GuillaumeHM,

This is not the right place to discuss this, so I created issue #3.

Cheers,
Nicolas

**Comment by swenner** [comment]
@Malizor yes, we should do a release. Maybe after fixing bug #3 ?

**Pull request merged**
